spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_db1?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456

  activiti:
    check-process-definitions: false
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

server:
  port: 8088
  
  
